/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viliki.virtuaalinenlintukirja.gui;

import java.io.IOException;
import javax.swing.ImageIcon;
import viliki.virtuaalinenlintukirja.logiikka.Lataajat.LinnunTietojenLatain;
import viliki.virtuaalinenlintukirja.logiikka.Lintu;

/**
 *
 * @author Eeki
 */
public class LinnunKuvausGui extends javax.swing.JFrame {

    private LinnunTietojenLatain latain;
    private Lintu lintu;

    public LinnunKuvausGui(Lintu lintu) {
        initComponents();
        this.lintu = lintu;
        latain = new LinnunTietojenLatain();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimiLabel = new javax.swing.JLabel();
        linnunKuva = new javax.swing.JLabel();
        kuvausTextArea = new javax.swing.JTextArea();
        latinaLabel = new javax.swing.JLabel();
        heimoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nimiLabel.setBackground(new java.awt.Color(255, 255, 255));
        nimiLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nimiLabel.setText("Nimi");

        linnunKuva.setBackground(new java.awt.Color(255, 255, 255));

        kuvausTextArea.setEditable(false);
        kuvausTextArea.setColumns(20);
        kuvausTextArea.setRows(5);

        latinaLabel.setBackground(new java.awt.Color(255, 255, 255));
        latinaLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        latinaLabel.setText("Latina");

        heimoLabel.setBackground(new java.awt.Color(255, 255, 255));
        heimoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heimoLabel.setText("Heimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(latinaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linnunKuva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nimiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(heimoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kuvausTextArea))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nimiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(latinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heimoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linnunKuva, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kuvausTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void asetaTiedot() throws IOException {
        this.nimiLabel.setText(this.lintu.getNimi());
        this.latinaLabel.setText("(" + this.lintu.getLatina() + ")");
        this.heimoLabel.setText("Heimo: " + this.lintu.getHeimo());
        this.linnunKuva.setIcon(new ImageIcon(latain.lataaKuva(lintu,"kuvat")));
        this.kuvausTextArea.setText(latain.lataaSelitys(lintu,"selitykset"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heimoLabel;
    private javax.swing.JTextArea kuvausTextArea;
    private javax.swing.JLabel latinaLabel;
    private javax.swing.JLabel linnunKuva;
    private javax.swing.JLabel nimiLabel;
    // End of variables declaration//GEN-END:variables
}
