/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viliki.virtuaalinenlintukirja.gui;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.nio.charset.Charset;
import javax.swing.ImageIcon;
import viliki.virtuaalinenlintukirja.logiikka.Lataajat.LinnunTietojenLatain;
import viliki.virtuaalinenlintukirja.logiikka.Lintu;

/**
 *
 * @author Eeki
 */
public class LinnunKuvausGui extends javax.swing.JFrame {

    private LinnunTietojenLatain latain;
    private Lintu lintu;

    /**
     *
     * @param lintu
     */
    public LinnunKuvausGui(Lintu lintu) {
        initComponents();
        this.lintu = lintu;
        latain = new LinnunTietojenLatain();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimiLabel = new javax.swing.JLabel();
        linnunKuva = new javax.swing.JLabel();
        latinaLabel = new javax.swing.JLabel();
        heimoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kuvausTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 600));

        nimiLabel.setBackground(new java.awt.Color(255, 255, 255));
        nimiLabel.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        nimiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nimiLabel.setText("Nimi");

        linnunKuva.setBackground(new java.awt.Color(255, 255, 255));
        linnunKuva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        latinaLabel.setBackground(new java.awt.Color(255, 255, 255));
        latinaLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        latinaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        latinaLabel.setText("Latina");

        heimoLabel.setBackground(new java.awt.Color(255, 255, 255));
        heimoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        heimoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heimoLabel.setText("Heimo");

        kuvausTextArea.setEditable(false);
        kuvausTextArea.setColumns(20);
        kuvausTextArea.setLineWrap(true);
        kuvausTextArea.setTabSize(0);
        kuvausTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(kuvausTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(latinaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heimoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nimiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(linnunKuva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nimiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(latinaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heimoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linnunKuva, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @throws IOException
     */
    public void asetaTiedot() throws IOException {
    String selitys = latain.lataaSelitys(lintu, "Resources/selitykset/");
    Charset.forName("UTF-8").encode(selitys);
    
//        String juttu = latain.lataaSelitys(lintu, "Resources/selitykset/");
//        byte[] b = juttu.getBytes("UTF-8");
//        InputStreamReader isr = new InputStreamReader(new ByteArrayInputStream((latain.lataaSelitys(lintu, "Resources/selitykset/")).getBytes()), "UTF-8");
//        BufferedReader br = new BufferedReader(isr);
//        String line = null;
//
//        while ((line = br.readLine()) != null) {
//            this.kuvausTextArea.setText(line);
//        }
//        String line = convertToUTF8(latain.lataaSelitys(lintu, "Resources/selitykset/"));
        this.kuvausTextArea.setText(selitys);



        this.nimiLabel.setText(this.lintu.getNimi());
        this.latinaLabel.setText("(" + this.lintu.getLatina() + ")");
        this.heimoLabel.setText("Heimo: " + this.lintu.getHeimo());
        this.linnunKuva.setIcon(new ImageIcon(latain.lataaKuva(lintu, "Resources/kuvat/")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heimoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea kuvausTextArea;
    private javax.swing.JLabel latinaLabel;
    private javax.swing.JLabel linnunKuva;
    private javax.swing.JLabel nimiLabel;
    // End of variables declaration//GEN-END:variables

public static String convertToUTF8(String s) {
        String out = null;
        try {
            out = new String(s.getBytes("UTF-8"), "ISO-8859-1");
        } catch (java.io.UnsupportedEncodingException e) {
            return null;
        }
        return out;
    }

}
