/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viliki.virtuaalinenlintukirja.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import viliki.virtuaalinenlintukirja.logiikka.Lintu;
import viliki.virtuaalinenlintukirja.logiikka.Lintukirja;
import viliki.virtuaalinenlintukirja.logiikka.TyokaluPakki;

public class LisaaLintuGui extends javax.swing.JFrame {

    JFileChooser tiedostonValitsin;
    Lintukirja lintukirja;

    public LisaaLintuGui(Lintukirja lintukirja) {
        initComponents();
        this.lintukirja = lintukirja;
        tiedostonValitsin = new JFileChooser();

    }

    private void lisaaLintu(String nimi, String latina, String heimo, String kuva, String kuvanlahde, String selitys) throws Exception {
        if (tarkistaTietojenOikeus()) {
            lintukirja.lisaaLintuTiedostoon(new Lintu(nimi, latina, heimo, kuva), kuvanlahde, TyokaluPakki.kuvaFormaatti(kuvanlahde), selitys);
        }
    }

    private boolean tarkistaTietojenOikeus() {
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNimi = new javax.swing.JTextField();
        jTextFieldLatina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHeimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonPeruuta = new javax.swing.JButton();
        jButtonLisaaTietokantaan = new javax.swing.JButton();
        jTextFieldKuvanPolku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSelitys = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lisää lintu");

        jTextFieldNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNimiActionPerformed(evt);
            }
        });

        jTextFieldLatina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatinaActionPerformed(evt);
            }
        });

        jLabel2.setText("Lisää linnulle nimi");

        jLabel3.setText("Lisää linnulle tieteellinen nimi");

        jTextFieldHeimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeimoActionPerformed(evt);
            }
        });

        jLabel4.setText("Lisää linnulle heimo");

        jButtonPeruuta.setText("Peruuta");
        jButtonPeruuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeruutaActionPerformed(evt);
            }
        });

        jButtonLisaaTietokantaan.setText("Lisaa tietokantaan");
        jButtonLisaaTietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLisaaTietokantaanActionPerformed(evt);
            }
        });

        jTextFieldKuvanPolku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKuvanPolkuActionPerformed(evt);
            }
        });

        jLabel5.setText("Lisää linnulle selitys");

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jTextAreaSelitys.setColumns(20);
        jTextAreaSelitys.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSelitys);

        jLabel6.setText("Lisää linnulle kuva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNimi)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLatina)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldHeimo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jButtonPeruuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLisaaTietokantaan))
                    .addComponent(jTextFieldKuvanPolku)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLatina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHeimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKuvanPolku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPeruuta)
                            .addComponent(jButtonLisaaTietokantaan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBrowse)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNimiActionPerformed

    private void jTextFieldLatinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLatinaActionPerformed

    private void jTextFieldHeimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeimoActionPerformed

    private void jTextFieldKuvanPolkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKuvanPolkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKuvanPolkuActionPerformed

    private void jButtonPeruutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeruutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPeruutaActionPerformed

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed

        this.tiedostonValitsin.showOpenDialog(null);
        try {
            String kuvanPolku = this.tiedostonValitsin.getSelectedFile().getAbsolutePath();
            if (!kuvanPolku.isEmpty()) {
                this.jTextFieldKuvanPolku.setText(kuvanPolku);
            }
        } catch (Exception e) {
            System.out.println("Ei valintaa");
        }



    }//GEN-LAST:event_jButtonBrowseActionPerformed
    private void jButtonLisaaTietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLisaaTietokantaanActionPerformed
        try {
            lisaaLintu(jTextFieldNimi.getText(), jTextFieldLatina.getText(), jTextFieldHeimo.getText(), TyokaluPakki.poistaSkandit(jTextFieldNimi.getText()), jTextFieldKuvanPolku.getText(), jTextAreaSelitys.getText());
        } catch (Exception ex) {
            TyokaluPakki.popUpViesti("Linnun lisääminen epäonnistui", "Lisaa lintu GUI");
            Logger
                    .getLogger(LisaaLintuGui.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLisaaTietokantaanActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonLisaaTietokantaan;
    private javax.swing.JButton jButtonPeruuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSelitys;
    private javax.swing.JTextField jTextFieldHeimo;
    private javax.swing.JTextField jTextFieldKuvanPolku;
    private javax.swing.JTextField jTextFieldLatina;
    private javax.swing.JTextField jTextFieldNimi;
    // End of variables declaration//GEN-END:variables
}
