/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viliki.virtuaalinenlintukirja.gui;

import javax.swing.JFileChooser;
import viliki.virtuaalinenlintukirja.logiikka.Lintukirja;


public class LisaaLintuGui extends javax.swing.JFrame {
    JFileChooser tiedostonValitsin;
    Lintukirja lintukirja;

    public LisaaLintuGui(Lintukirja lintukirja) {
        initComponents();
        this.lintukirja = lintukirja;
        tiedostonValitsin = new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNimi = new javax.swing.JTextField();
        jTextFieldLatina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHeimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonPeruuta = new javax.swing.JButton();
        jButtonLisaaTietokantaan = new javax.swing.JButton();
        jTextFieldkuvanPolku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lisää lintu");

        jTextFieldNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNimiActionPerformed(evt);
            }
        });

        jTextFieldLatina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatinaActionPerformed(evt);
            }
        });

        jLabel2.setText("Lisää linnulle nimi");

        jLabel3.setText("Lisää linnulle tieteellinen nimi");

        jTextFieldHeimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeimoActionPerformed(evt);
            }
        });

        jLabel4.setText("Lisää linnulle heimo");

        jButtonPeruuta.setText("Peruuta");
        jButtonPeruuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeruutaActionPerformed(evt);
            }
        });

        jButtonLisaaTietokantaan.setText("Lisaa tietokantaan");

        jTextFieldkuvanPolku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldkuvanPolkuActionPerformed(evt);
            }
        });

        jLabel5.setText("Lisää linnulle kuva");

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNimi)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLatina)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldHeimo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldkuvanPolku)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonPeruuta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 141, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLisaaTietokantaan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLatina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHeimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldkuvanPolku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBrowse)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPeruuta)
                    .addComponent(jButtonLisaaTietokantaan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNimiActionPerformed

    private void jTextFieldLatinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLatinaActionPerformed

    private void jTextFieldHeimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeimoActionPerformed

    private void jTextFieldkuvanPolkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldkuvanPolkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldkuvanPolkuActionPerformed

    private void jButtonPeruutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeruutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPeruutaActionPerformed

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonLisaaTietokantaan;
    private javax.swing.JButton jButtonPeruuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldHeimo;
    private javax.swing.JTextField jTextFieldLatina;
    private javax.swing.JTextField jTextFieldNimi;
    private javax.swing.JTextField jTextFieldkuvanPolku;
    // End of variables declaration//GEN-END:variables
}
